Repository bredbrains/tthk-wish-list, pull requests merged in 2021-05, with the labels that each got.

#4 Features/100 database api
  .github/workflows/go.yml
  database/database.go
  endpoints/auth/login.go
  endpoints/auth/register.go
  endpoints/auth/user.go
  endpoints/follows/add.go
  endpoints/follows/delete.go
  endpoints/wishes/add.go
  endpoints/wishes/delete.go
  endpoints/wishes/hide.go
  endpoints/wishes/recieve.go
  endpoints/wishes/suggestion.go
  endpoints/wishes/update.go
  go.mod
  go.sum
  main.go
  models/follow.go
  models/user.go
  models/wish.go
Labels: enhancement

#7 Add deleting wish feature with permissions check and migrate to new naming convention.
  database/database.go
  endpoints/wishes/delete.go
  main.go
Labels: enhancement

#8 Profile edit validation requires JSON validation & error catching.
  endpoints/users/profile.go
Labels: bug, invalid

#10 Add toggled followed and unfollowed.
  database/database.go
  endpoints/follows/add.go
  endpoints/follows/delete.go
  main.go
  modules/checkFollow.go
Labels: enhancement

#11 #144 - A lot of places in code uses different types of int.
  endpoints/follows/add.go
  models/follow.go
  models/wish.go
Labels: bug, invalid

#18 Version 2021.2.0
  database/database.go
  endpoints/auth/register.go
  endpoints/feedback/comments/add.go
  endpoints/feedback/comments/comment.go
  endpoints/feedback/comments/delete.go
  endpoints/feedback/comments/update.go
  endpoints/feedback/like.go
  endpoints/follows/add.go
  endpoints/follows/delete.go
  endpoints/wishes/add.go
  endpoints/wishes/delete.go
  endpoints/wishes/recieve.go
  endpoints/wishes/suggestion.go
  endpoints/wishes/update.go
  main.go
  models/comment.go
  models/like.go
  models/wish.go
  tests/manual/.gitignore
  tests/manual/like.py
Labels: new version
